### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'timestep_limit'

### ISSUE THREAD

**Issue by Papul-Ghosh** [hjalte33/rl_project#2]
Hi, I am working on ubuntu 18.04, ros version melodic, I followed the execution of the commands from the readme file. The last command (executing simple_loop.py) is showing me some error as:

Traceback (most recent call last):
  File "src/rl_unscrew/rl-gym/simple_loop.py", line 12, in <module>
    import rl_gym
  File "/home/herrghosh/catkin_ws/src/rl_unscrew/rl-gym/rl_gym/__init__.py", line 6, in <module>
    timestep_limit = 200
  File "/home/herrghosh/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 139, in register
    return registry.register(id, **kwargs)
  File "/home/herrghosh/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 133, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timestep_limit'
